name: correios_frete
description: Calcular o Preço e o Prazo da Entregas de encomendas pelo SEDEX e PAC
version: 0.0.1
author: Felipe Mourão<lipemourao6@gmail.com>
homepage: https://github.com/FelipeMourao/correios-frete.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  xml2json: ^4.1.1